apiVersion: jenkins.io/v1
kind: Scheduler
metadata:
  creationTimestamp: null
  name: release-only
spec:
  approve:
    issueRequired: false
    lgtmActsAsApprove: true
    requireSelfApproval: true
  merger:
    blockerLabel: ""
    maxGoroutines: 0
    mergeMethod: merge
    policy:
      fromBranchProtection: true
      optionalContexts: {}
      requiredContexts: {}
      requiredIfPresentContexts: {}
      skipUnknownContexts: false
    prStatusBaseUrl: ""
    squashLabel: ""
    targetUrl: http://deck{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
  plugins:
    entries:
    - approve
    - assign
    - blunderbuss
    - help
    - hold
    - lgtm
    - lifecycle
    - override
    - size
    - trigger
    - wip
    - heart
    - cat
    - dog
    - pony
  policy:
    protectTested: true
  postsubmits:
    entries:
    - agent: tekton
      branches:
        entries:
        - ^master$
      cluster: ""
      context: ""
      labels: {}
      maxConcurrency: 0
      name: release
      report: false
      runIfChanged: ""
      skipBranches: {}
  schedulerAgent:
    agent: tekton
  trigger:
    ignoreOkToTest: false
    joinOrgUrl: ""
    onlyOrgMembers: false
    trustedOrg: {{ .Values.gitops.owner }}
  welcome:
  - message_template: Welcome
